=begin
Vericred API

Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Most endpoints are not paginated.  It will be noted in the documentation if/when
an endpoint is paginated.

When pagination is present, a `meta` stanza will be present in the response
with the total number of records

```
{
  things: [{ id: 1 }, { id: 2 }],
  meta: { total: 500 }
}
```

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```



OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module VericredClient
  class Plan
    # Does the plan provide dental coverage for adults?
    attr_accessor :adult_dental

    # Benefits string for ambulance coverage
    attr_accessor :ambulance

    # Link to the summary of benefits and coverage (SBC) document.
    attr_accessor :benefits_summary_url

    # Link to a location to purchase the plan.
    attr_accessor :buy_link

    # Name of the insurance carrier
    attr_accessor :carrier_name

    # Does the plan provide dental coverage for children?
    attr_accessor :child_dental

    # Child eyewear benefits summary
    attr_accessor :child_eyewear

    # Child eye exam benefits summary
    attr_accessor :child_eye_exam

    # Phone number to contact the insurance carrier
    attr_accessor :customer_service_phone_number

    # Benefits summary for durable medical equipment
    attr_accessor :durable_medical_equipment

    # Diagnostic tests benefit summary
    attr_accessor :diagnostic_test

    # Link to the summary of drug benefits for the plan
    attr_accessor :drug_formulary_url

    # Effective date of coverage.
    attr_accessor :effective_date

    # Expiration date of coverage.
    attr_accessor :expiration_date

    # Description of costs when visiting the ER
    attr_accessor :emergency_room

    # Deductible for drugs when a family is on the plan.
    attr_accessor :family_drug_deductible

    # Maximum out-of-pocket for drugs when a family is on the plan
    attr_accessor :family_drug_moop

    # Deductible when a family is on the plan
    attr_accessor :family_medical_deductible

    # Maximum out-of-pocket when a family is on the plan
    attr_accessor :family_medical_moop

    # Cost for generic drugs
    attr_accessor :generic_drugs

    # Habilitation services benefits summary
    attr_accessor :habilitation_services

    # 
    attr_accessor :hios_issuer_id

    # Home health care benefits summary
    attr_accessor :home_health_care

    # Hospice service benefits summary
    attr_accessor :hospice_service

    # Government-issued HIOS plan ID
    attr_accessor :id

    # Benefits summary for imaging coverage
    attr_accessor :imaging

    # List of NPI numbers for Providers passed in who accept this Plan
    attr_accessor :in_network_ids

    # Deductible for drugs when an individual is on the plan
    attr_accessor :individual_drug_deductible

    # Maximum out-of-pocket for drugs when an individual is on the plan
    attr_accessor :individual_drug_moop

    # Deductible when an individual is on the plan
    attr_accessor :individual_medical_deductible

    # Maximum out-of-pocket when an individual is on the plan
    attr_accessor :individual_medical_moop

    # Inpatient birth benefits summary
    attr_accessor :inpatient_birth

    # Cost under the plan for an inpatient facility
    attr_accessor :inpatient_facility

    # Inpatient mental helath benefits summary
    attr_accessor :inpatient_mental_health

    # Cost under the plan for an inpatient physician
    attr_accessor :inpatient_physician

    # Inpatient substance abuse benefits summary
    attr_accessor :inpatient_substance

    # Plan metal grouping (e.g. platinum, gold, silver, etc)
    attr_accessor :level

    # Link to a copy of the insurance carrier's logo
    attr_accessor :logo_url

    # Marketing name of the plan
    attr_accessor :name

    # Total number of Providers in network
    attr_accessor :network_size

    # Cost under the plan for non-preferred brand drugs
    attr_accessor :non_preferred_brand_drugs

    # Is the plan on-market?
    attr_accessor :on_market

    # Is the plan off-market?
    attr_accessor :off_market

    # Does this plan provide any out of network coverage?
    attr_accessor :out_of_network_coverage

    # List of NPI numbers for Providers passed in who do not accept this Plan
    attr_accessor :out_of_network_ids

    # Benefits summary for outpatient facility coverage
    attr_accessor :outpatient_facility

    # Benefits summary for outpatient mental health coverage
    attr_accessor :outpatient_mental_health

    # Benefits summary for outpatient physician coverage
    attr_accessor :outpatient_physician

    # Outpatient substance abuse benefits summary
    attr_accessor :outpatient_substance

    # Market in which the plan is offered (on_marketplace, shop, etc)
    attr_accessor :plan_market

    # Category of the plan (e.g. EPO, HMO, PPO, POS, Indemnity)
    attr_accessor :plan_type

    # Cost under the plan for perferred brand drugs
    attr_accessor :preferred_brand_drugs

    # Inpatient substance abuse benefits summary
    attr_accessor :prenatal_postnatal_care

    # Benefits summary for preventative care
    attr_accessor :preventative_care

    # Cumulative premium amount after subsidy
    attr_accessor :premium_subsidized

    # Cumulative premium amount
    attr_accessor :premium

    # Cost under the plan to visit a Primary Care Physician
    attr_accessor :primary_care_physician

    # Benefits summary for rehabilitation services
    attr_accessor :rehabilitation_services

    # Benefits summary for skilled nursing services
    attr_accessor :skilled_nursing

    # Cost under the plan to visit a specialist
    attr_accessor :specialist

    # Cost under the plan for specialty drugs
    attr_accessor :specialty_drugs

    # Benefits summary for urgent care
    attr_accessor :urgent_care

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'adult_dental' => :'adult_dental',
        :'ambulance' => :'ambulance',
        :'benefits_summary_url' => :'benefits_summary_url',
        :'buy_link' => :'buy_link',
        :'carrier_name' => :'carrier_name',
        :'child_dental' => :'child_dental',
        :'child_eyewear' => :'child_eyewear',
        :'child_eye_exam' => :'child_eye_exam',
        :'customer_service_phone_number' => :'customer_service_phone_number',
        :'durable_medical_equipment' => :'durable_medical_equipment',
        :'diagnostic_test' => :'diagnostic_test',
        :'drug_formulary_url' => :'drug_formulary_url',
        :'effective_date' => :'effective_date',
        :'expiration_date' => :'expiration_date',
        :'emergency_room' => :'emergency_room',
        :'family_drug_deductible' => :'family_drug_deductible',
        :'family_drug_moop' => :'family_drug_moop',
        :'family_medical_deductible' => :'family_medical_deductible',
        :'family_medical_moop' => :'family_medical_moop',
        :'generic_drugs' => :'generic_drugs',
        :'habilitation_services' => :'habilitation_services',
        :'hios_issuer_id' => :'hios_issuer_id',
        :'home_health_care' => :'home_health_care',
        :'hospice_service' => :'hospice_service',
        :'id' => :'id',
        :'imaging' => :'imaging',
        :'in_network_ids' => :'in_network_ids',
        :'individual_drug_deductible' => :'individual_drug_deductible',
        :'individual_drug_moop' => :'individual_drug_moop',
        :'individual_medical_deductible' => :'individual_medical_deductible',
        :'individual_medical_moop' => :'individual_medical_moop',
        :'inpatient_birth' => :'inpatient_birth',
        :'inpatient_facility' => :'inpatient_facility',
        :'inpatient_mental_health' => :'inpatient_mental_health',
        :'inpatient_physician' => :'inpatient_physician',
        :'inpatient_substance' => :'inpatient_substance',
        :'level' => :'level',
        :'logo_url' => :'logo_url',
        :'name' => :'name',
        :'network_size' => :'network_size',
        :'non_preferred_brand_drugs' => :'non_preferred_brand_drugs',
        :'on_market' => :'on_market',
        :'off_market' => :'off_market',
        :'out_of_network_coverage' => :'out_of_network_coverage',
        :'out_of_network_ids' => :'out_of_network_ids',
        :'outpatient_facility' => :'outpatient_facility',
        :'outpatient_mental_health' => :'outpatient_mental_health',
        :'outpatient_physician' => :'outpatient_physician',
        :'outpatient_substance' => :'outpatient_substance',
        :'plan_market' => :'plan_market',
        :'plan_type' => :'plan_type',
        :'preferred_brand_drugs' => :'preferred_brand_drugs',
        :'prenatal_postnatal_care' => :'prenatal_postnatal_care',
        :'preventative_care' => :'preventative_care',
        :'premium_subsidized' => :'premium_subsidized',
        :'premium' => :'premium',
        :'primary_care_physician' => :'primary_care_physician',
        :'rehabilitation_services' => :'rehabilitation_services',
        :'skilled_nursing' => :'skilled_nursing',
        :'specialist' => :'specialist',
        :'specialty_drugs' => :'specialty_drugs',
        :'urgent_care' => :'urgent_care'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'adult_dental' => :'BOOLEAN',
        :'ambulance' => :'String',
        :'benefits_summary_url' => :'String',
        :'buy_link' => :'String',
        :'carrier_name' => :'String',
        :'child_dental' => :'BOOLEAN',
        :'child_eyewear' => :'String',
        :'child_eye_exam' => :'String',
        :'customer_service_phone_number' => :'String',
        :'durable_medical_equipment' => :'String',
        :'diagnostic_test' => :'String',
        :'drug_formulary_url' => :'String',
        :'effective_date' => :'String',
        :'expiration_date' => :'String',
        :'emergency_room' => :'String',
        :'family_drug_deductible' => :'String',
        :'family_drug_moop' => :'String',
        :'family_medical_deductible' => :'String',
        :'family_medical_moop' => :'String',
        :'generic_drugs' => :'String',
        :'habilitation_services' => :'String',
        :'hios_issuer_id' => :'String',
        :'home_health_care' => :'String',
        :'hospice_service' => :'String',
        :'id' => :'String',
        :'imaging' => :'String',
        :'in_network_ids' => :'Array<Integer>',
        :'individual_drug_deductible' => :'String',
        :'individual_drug_moop' => :'String',
        :'individual_medical_deductible' => :'String',
        :'individual_medical_moop' => :'String',
        :'inpatient_birth' => :'String',
        :'inpatient_facility' => :'String',
        :'inpatient_mental_health' => :'String',
        :'inpatient_physician' => :'String',
        :'inpatient_substance' => :'String',
        :'level' => :'String',
        :'logo_url' => :'String',
        :'name' => :'String',
        :'network_size' => :'Integer',
        :'non_preferred_brand_drugs' => :'String',
        :'on_market' => :'BOOLEAN',
        :'off_market' => :'BOOLEAN',
        :'out_of_network_coverage' => :'BOOLEAN',
        :'out_of_network_ids' => :'Array<Integer>',
        :'outpatient_facility' => :'String',
        :'outpatient_mental_health' => :'String',
        :'outpatient_physician' => :'String',
        :'outpatient_substance' => :'String',
        :'plan_market' => :'String',
        :'plan_type' => :'String',
        :'preferred_brand_drugs' => :'String',
        :'prenatal_postnatal_care' => :'String',
        :'preventative_care' => :'String',
        :'premium_subsidized' => :'Float',
        :'premium' => :'Float',
        :'primary_care_physician' => :'String',
        :'rehabilitation_services' => :'String',
        :'skilled_nursing' => :'String',
        :'specialist' => :'String',
        :'specialty_drugs' => :'String',
        :'urgent_care' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'adult_dental')
        self.adult_dental = attributes[:'adult_dental']
      end

      if attributes.has_key?(:'ambulance')
        self.ambulance = attributes[:'ambulance']
      end

      if attributes.has_key?(:'benefits_summary_url')
        self.benefits_summary_url = attributes[:'benefits_summary_url']
      end

      if attributes.has_key?(:'buy_link')
        self.buy_link = attributes[:'buy_link']
      end

      if attributes.has_key?(:'carrier_name')
        self.carrier_name = attributes[:'carrier_name']
      end

      if attributes.has_key?(:'child_dental')
        self.child_dental = attributes[:'child_dental']
      end

      if attributes.has_key?(:'child_eyewear')
        self.child_eyewear = attributes[:'child_eyewear']
      end

      if attributes.has_key?(:'child_eye_exam')
        self.child_eye_exam = attributes[:'child_eye_exam']
      end

      if attributes.has_key?(:'customer_service_phone_number')
        self.customer_service_phone_number = attributes[:'customer_service_phone_number']
      end

      if attributes.has_key?(:'durable_medical_equipment')
        self.durable_medical_equipment = attributes[:'durable_medical_equipment']
      end

      if attributes.has_key?(:'diagnostic_test')
        self.diagnostic_test = attributes[:'diagnostic_test']
      end

      if attributes.has_key?(:'drug_formulary_url')
        self.drug_formulary_url = attributes[:'drug_formulary_url']
      end

      if attributes.has_key?(:'effective_date')
        self.effective_date = attributes[:'effective_date']
      end

      if attributes.has_key?(:'expiration_date')
        self.expiration_date = attributes[:'expiration_date']
      end

      if attributes.has_key?(:'emergency_room')
        self.emergency_room = attributes[:'emergency_room']
      end

      if attributes.has_key?(:'family_drug_deductible')
        self.family_drug_deductible = attributes[:'family_drug_deductible']
      end

      if attributes.has_key?(:'family_drug_moop')
        self.family_drug_moop = attributes[:'family_drug_moop']
      end

      if attributes.has_key?(:'family_medical_deductible')
        self.family_medical_deductible = attributes[:'family_medical_deductible']
      end

      if attributes.has_key?(:'family_medical_moop')
        self.family_medical_moop = attributes[:'family_medical_moop']
      end

      if attributes.has_key?(:'generic_drugs')
        self.generic_drugs = attributes[:'generic_drugs']
      end

      if attributes.has_key?(:'habilitation_services')
        self.habilitation_services = attributes[:'habilitation_services']
      end

      if attributes.has_key?(:'hios_issuer_id')
        self.hios_issuer_id = attributes[:'hios_issuer_id']
      end

      if attributes.has_key?(:'home_health_care')
        self.home_health_care = attributes[:'home_health_care']
      end

      if attributes.has_key?(:'hospice_service')
        self.hospice_service = attributes[:'hospice_service']
      end

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'imaging')
        self.imaging = attributes[:'imaging']
      end

      if attributes.has_key?(:'in_network_ids')
        if (value = attributes[:'in_network_ids']).is_a?(Array)
          self.in_network_ids = value
        end
      end

      if attributes.has_key?(:'individual_drug_deductible')
        self.individual_drug_deductible = attributes[:'individual_drug_deductible']
      end

      if attributes.has_key?(:'individual_drug_moop')
        self.individual_drug_moop = attributes[:'individual_drug_moop']
      end

      if attributes.has_key?(:'individual_medical_deductible')
        self.individual_medical_deductible = attributes[:'individual_medical_deductible']
      end

      if attributes.has_key?(:'individual_medical_moop')
        self.individual_medical_moop = attributes[:'individual_medical_moop']
      end

      if attributes.has_key?(:'inpatient_birth')
        self.inpatient_birth = attributes[:'inpatient_birth']
      end

      if attributes.has_key?(:'inpatient_facility')
        self.inpatient_facility = attributes[:'inpatient_facility']
      end

      if attributes.has_key?(:'inpatient_mental_health')
        self.inpatient_mental_health = attributes[:'inpatient_mental_health']
      end

      if attributes.has_key?(:'inpatient_physician')
        self.inpatient_physician = attributes[:'inpatient_physician']
      end

      if attributes.has_key?(:'inpatient_substance')
        self.inpatient_substance = attributes[:'inpatient_substance']
      end

      if attributes.has_key?(:'level')
        self.level = attributes[:'level']
      end

      if attributes.has_key?(:'logo_url')
        self.logo_url = attributes[:'logo_url']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'network_size')
        self.network_size = attributes[:'network_size']
      end

      if attributes.has_key?(:'non_preferred_brand_drugs')
        self.non_preferred_brand_drugs = attributes[:'non_preferred_brand_drugs']
      end

      if attributes.has_key?(:'on_market')
        self.on_market = attributes[:'on_market']
      end

      if attributes.has_key?(:'off_market')
        self.off_market = attributes[:'off_market']
      end

      if attributes.has_key?(:'out_of_network_coverage')
        self.out_of_network_coverage = attributes[:'out_of_network_coverage']
      end

      if attributes.has_key?(:'out_of_network_ids')
        if (value = attributes[:'out_of_network_ids']).is_a?(Array)
          self.out_of_network_ids = value
        end
      end

      if attributes.has_key?(:'outpatient_facility')
        self.outpatient_facility = attributes[:'outpatient_facility']
      end

      if attributes.has_key?(:'outpatient_mental_health')
        self.outpatient_mental_health = attributes[:'outpatient_mental_health']
      end

      if attributes.has_key?(:'outpatient_physician')
        self.outpatient_physician = attributes[:'outpatient_physician']
      end

      if attributes.has_key?(:'outpatient_substance')
        self.outpatient_substance = attributes[:'outpatient_substance']
      end

      if attributes.has_key?(:'plan_market')
        self.plan_market = attributes[:'plan_market']
      end

      if attributes.has_key?(:'plan_type')
        self.plan_type = attributes[:'plan_type']
      end

      if attributes.has_key?(:'preferred_brand_drugs')
        self.preferred_brand_drugs = attributes[:'preferred_brand_drugs']
      end

      if attributes.has_key?(:'prenatal_postnatal_care')
        self.prenatal_postnatal_care = attributes[:'prenatal_postnatal_care']
      end

      if attributes.has_key?(:'preventative_care')
        self.preventative_care = attributes[:'preventative_care']
      end

      if attributes.has_key?(:'premium_subsidized')
        self.premium_subsidized = attributes[:'premium_subsidized']
      end

      if attributes.has_key?(:'premium')
        self.premium = attributes[:'premium']
      end

      if attributes.has_key?(:'primary_care_physician')
        self.primary_care_physician = attributes[:'primary_care_physician']
      end

      if attributes.has_key?(:'rehabilitation_services')
        self.rehabilitation_services = attributes[:'rehabilitation_services']
      end

      if attributes.has_key?(:'skilled_nursing')
        self.skilled_nursing = attributes[:'skilled_nursing']
      end

      if attributes.has_key?(:'specialist')
        self.specialist = attributes[:'specialist']
      end

      if attributes.has_key?(:'specialty_drugs')
        self.specialty_drugs = attributes[:'specialty_drugs']
      end

      if attributes.has_key?(:'urgent_care')
        self.urgent_care = attributes[:'urgent_care']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared 
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          adult_dental == o.adult_dental &&
          ambulance == o.ambulance &&
          benefits_summary_url == o.benefits_summary_url &&
          buy_link == o.buy_link &&
          carrier_name == o.carrier_name &&
          child_dental == o.child_dental &&
          child_eyewear == o.child_eyewear &&
          child_eye_exam == o.child_eye_exam &&
          customer_service_phone_number == o.customer_service_phone_number &&
          durable_medical_equipment == o.durable_medical_equipment &&
          diagnostic_test == o.diagnostic_test &&
          drug_formulary_url == o.drug_formulary_url &&
          effective_date == o.effective_date &&
          expiration_date == o.expiration_date &&
          emergency_room == o.emergency_room &&
          family_drug_deductible == o.family_drug_deductible &&
          family_drug_moop == o.family_drug_moop &&
          family_medical_deductible == o.family_medical_deductible &&
          family_medical_moop == o.family_medical_moop &&
          generic_drugs == o.generic_drugs &&
          habilitation_services == o.habilitation_services &&
          hios_issuer_id == o.hios_issuer_id &&
          home_health_care == o.home_health_care &&
          hospice_service == o.hospice_service &&
          id == o.id &&
          imaging == o.imaging &&
          in_network_ids == o.in_network_ids &&
          individual_drug_deductible == o.individual_drug_deductible &&
          individual_drug_moop == o.individual_drug_moop &&
          individual_medical_deductible == o.individual_medical_deductible &&
          individual_medical_moop == o.individual_medical_moop &&
          inpatient_birth == o.inpatient_birth &&
          inpatient_facility == o.inpatient_facility &&
          inpatient_mental_health == o.inpatient_mental_health &&
          inpatient_physician == o.inpatient_physician &&
          inpatient_substance == o.inpatient_substance &&
          level == o.level &&
          logo_url == o.logo_url &&
          name == o.name &&
          network_size == o.network_size &&
          non_preferred_brand_drugs == o.non_preferred_brand_drugs &&
          on_market == o.on_market &&
          off_market == o.off_market &&
          out_of_network_coverage == o.out_of_network_coverage &&
          out_of_network_ids == o.out_of_network_ids &&
          outpatient_facility == o.outpatient_facility &&
          outpatient_mental_health == o.outpatient_mental_health &&
          outpatient_physician == o.outpatient_physician &&
          outpatient_substance == o.outpatient_substance &&
          plan_market == o.plan_market &&
          plan_type == o.plan_type &&
          preferred_brand_drugs == o.preferred_brand_drugs &&
          prenatal_postnatal_care == o.prenatal_postnatal_care &&
          preventative_care == o.preventative_care &&
          premium_subsidized == o.premium_subsidized &&
          premium == o.premium &&
          primary_care_physician == o.primary_care_physician &&
          rehabilitation_services == o.rehabilitation_services &&
          skilled_nursing == o.skilled_nursing &&
          specialist == o.specialist &&
          specialty_drugs == o.specialty_drugs &&
          urgent_care == o.urgent_care
    end

    # @see the `==` method
    # @param [Object] Object to be compared 
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [adult_dental, ambulance, benefits_summary_url, buy_link, carrier_name, child_dental, child_eyewear, child_eye_exam, customer_service_phone_number, durable_medical_equipment, diagnostic_test, drug_formulary_url, effective_date, expiration_date, emergency_room, family_drug_deductible, family_drug_moop, family_medical_deductible, family_medical_moop, generic_drugs, habilitation_services, hios_issuer_id, home_health_care, hospice_service, id, imaging, in_network_ids, individual_drug_deductible, individual_drug_moop, individual_medical_deductible, individual_medical_moop, inpatient_birth, inpatient_facility, inpatient_mental_health, inpatient_physician, inpatient_substance, level, logo_url, name, network_size, non_preferred_brand_drugs, on_market, off_market, out_of_network_coverage, out_of_network_ids, outpatient_facility, outpatient_mental_health, outpatient_physician, outpatient_substance, plan_market, plan_type, preferred_brand_drugs, prenatal_postnatal_care, preventative_care, premium_subsidized, premium, primary_care_physician, rehabilitation_services, skilled_nursing, specialist, specialty_drugs, urgent_care].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = VericredClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value 
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
